### ISSUE TITLE
Time Benchmark

### ISSUE THREAD

**Issue by DonaldTsang** [qntm/base2048#1]
Requesting comparison between this and http://blog.kevinalbs.com/base122 and http://base91.sourceforge.net/

**Comment by qntm** [comment]
By "Time Benchmark", do you mean throughput performance comparisons?

**Comment by DonaldTsang** [comment]
@qntm I meant encoding/decoding speed and data transfer speeds.

**Comment by qntm** [comment]
Ah. Well, I'm afraid I'm going to have to decline. It seems like a lot of work for an encoder which is written in JavaScript and intended to encode around 385 bytes at a time... and not used by anybody that I'm aware of...
