### ISSUE TITLE
[Discuss] Is there any  encode & decode functions in ohter coding languages? 

### ISSUE THREAD

**Issue by No54** [qntm/base2048#42]
Hi , I tried this repo from starter, and find it so nice !

Is there any  encode & decode functions in ohter coding languages? 

So that we can submit a string to backend and then using other coding language to decode it ! 

Thanks!

**Comment by qntm** [comment]
This repository is for `base2048`, a JavaScript implementation of the Base2048 encoding. There may be implementations of Base2048 in other programming languages but if there are I haven't been told about them. I suggest a Google search.
