### ISSUE TITLE
a version of the python

### ISSUE THREAD

**Issue by zerorzeror** [qntm/base2048#50]
Will the author write a version of the python

**Comment by qntm** [comment]
No, this is a JavaScript project. The encoding is pretty straightforward so it would be very simple to port it to Python, but I'm not going to do it. Thanks for your question.

**Comment by ross-spencer** [comment]
@zerorzeror there do seem to be some Python implementations of base2048, e.g. https://github.com/ionite34/base2048 -- thx for the reminder to give it a whirl!
